### PR TITLE
Updated the readme docs.

### PR DESCRIPTION
**Pull request by yahu1031**
**- What I did**
- Wrote the docs according to the exported files.

**- How I did it**
- Checked and write the content.

**- How to verify it**
- Read the docs.

**- Description for the changelog**

- Update the Readme file.

### CODE REVIEW

**Review by CynthiaPeter — DISMISSED** [review]
Hello @yahu1031 I made some minor changes and made some corrections concerning misspellings.

However, @cpswan, @nickelskevin, @gkc can anyone take some time to review this and give us some feedback?

Thank you.

**Comment by yahu1031** [comment]
@CynthiaPeter You requested some changes but couldn't find any. Can you please make sure of it again?

**Comment by cpswan** [comment]
@CynthiaPeter (and @yahu1031) I had a bunch of copy edits - more than made sense to leave a trail of comments. So I've made them and pushed 9dd87c1 and 8d26c39 to this PR branch. Please check through before merging.

The main things were:
- line length <80
- consistent spacing around (sub) headings

**Review by gkc — APPROVED** [review]

**Comment by yahu1031** [comment]
I need to check the example app. Will check and update the necessary changes. And then we can merge.

**Pull request merged**
