### PR TITLE
fix: at_commons:4.0.1 uptake and increased pub points [at_onboarding_flutter]

### PR DESCRIPTION
**Pull request by Sardar1208**
**- What I did - updated all dependencies (including at_commons: 4.0.1) and fixed formatting**
at_commons ticket link - https://github.com/atsign-foundation/at_widgets/issues/794
pub points ticket - https://github.com/atsign-foundation/apps/issues/780

### CODE REVIEW

**Review by sonle-geekyants — APPROVED** [review]

**Review by sachins-geekyants — APPROVED** [review]

**Comment by gkc** [comment]
@sachins-geekyants Why was it OK to merge the PR even though the melos-bootstrap check failed?

**Comment by Sardar1208** [comment]
@gkc The deps conflict shown here is not happening when we go a `flutter pub get`.

Screenshot 2024-02-07 at 5 40 02 PM

**Comment by gkc** [comment]
> @gkc The deps conflict shown here is not happening when we go a `flutter pub get`.

OK ... would be good to know why the melos-bootstrap check is failing though

**Comment by sachins-geekyants** [comment]
melos-bootstrap issue was reproduced locally in `at_contacts_flutter package` because of at_common conflict between onboarding and contact_flutter package.

In next PR, these conflicts will be reolved.

cc: @gkc

**Comment by gkc** [comment]
> melos-bootstrap issue was reproduced locally in `at_contacts_flutter package` because of at_common conflict between onboarding and contact_flutter package.
> 
> In next PR, these conflicts will be reolved.
> 
> cc: @gkc

Thanks @sachins-geekyants

**Pull request merged**
